language: python
sudo: required
dist: trusty
python:
    - 3.6.0
addons:
  apt:
    sources:
        - ubuntu-toolchain-r-test
    packages:
        - gcc-4.8
        - g++-4.8
        - libusb-1.0-0-dev
install:
    - pip install neologdn
    - pip install pandas
script:
    python -m doctest *.py
